# Generated by Django 3.2 on 2022-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220115_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
