# Generated by Django 3.2 on 2022-01-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220115_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cp_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
