# Generated by Django 3.2 on 2022-01-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220115_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cp_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
